library(dplyr)
aqidiff <- read.delim("data.txt", header = TRUE)
aqidiff <- aqidiff %>% mutate(aqi_diff = US_AQI - China_AQI)
summary(aqidiff)
aa<-which(is.na(aqidiff[,2]))
aqidiff1<-aqidiff[-aa,]

zeromean<-aqidiff1$aqi_diff-mean(aqidiff1$aqi_diff)
ts.plot(zeromean)
library(urca)
summary(ur.df(diff(zeromean),lag=0,type="none"))
summary(ur.df(diff(zeromean),lag=1,type="none"))
summary(ur.df(diff(zeromean),lag=2,type="none"))
summary(ur.df(diff(zeromean),lag=0,type="drift"))
summary(ur.df(diff(zeromean),lag=1,type="drift"))
summary(ur.df(diff(zeromean),lag=2,type="drift"))
summary(ur.df(diff(zeromean),lag=0,type="trend"))
summary(ur.df(diff(zeromean),lag=1,type="trend"))
summary(ur.df(diff(zeromean),lag=2,type="trend"))
